name: Build & Push Cloudy Runner

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  IMAGE: engabelal/cloudy-runner

jobs:
  amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push amd64
        run: |
          set -a
          source versions.env
          set +a

          docker build \
            --pull \
            -f docker/Dockerfile.amd64 \
            --build-arg NODE_VERSION \
            --build-arg TERRAFORM_VERSION \
            --build-arg ANSIBLE_VERSION \
            --build-arg KUBECTL_VERSION \
            --build-arg HELM_VERSION \
            --build-arg KUSTOMIZE_VERSION \
            --build-arg YQ_VERSION \
            -t $IMAGE:amd64 \
            -t $IMAGE:${GITHUB_REF_NAME}-amd64 \
            .

          docker push $IMAGE:amd64
          docker push $IMAGE:${GITHUB_REF_NAME}-amd64

  arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push arm64
        run: |
          set -a
          source versions.env
          set +a

          docker build \
            --pull \
            -f docker/Dockerfile.arm64 \
            --build-arg NODE_VERSION \
            --build-arg TERRAFORM_VERSION \
            --build-arg ANSIBLE_VERSION \
            --build-arg KUBECTL_VERSION \
            --build-arg HELM_VERSION \
            --build-arg KUSTOMIZE_VERSION \
            --build-arg YQ_VERSION \
            -t $IMAGE:arm64 \
            -t $IMAGE:${GITHUB_REF_NAME}-arm64 \
            .

          docker push $IMAGE:arm64
          docker push $IMAGE:${GITHUB_REF_NAME}-arm64
