name: Build Cloudy Runner Images

on:
  push:
    branches: [ main ]

env:
  IMAGE: engabelal/cloudy-runner

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: grep -v '^#' versions.env >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            -f docker/Dockerfile.amd64 \
            -t $IMAGE:amd64 \
            $(printf -- '--build-arg %s ' $(cat versions.env | grep -v '^#')) .
          docker push $IMAGE:amd64

  arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: grep -v '^#' versions.env >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            -f docker/Dockerfile.arm64 \
            -t $IMAGE:arm64 \
            $(printf -- '--build-arg %s ' $(cat versions.env | grep -v '^#')) .
          docker push $IMAGE:arm64
